docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Usage: usage.md
    - Adapters: adapters.md
site_name: laminas-captcha
site_description: laminas-captcha
repo_url: 'https://github.com/laminas/laminas-captcha'
